version: "3.8"
services:
  api:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: "postgres"
    ports:
      - 5432:5432
    #env_file:
    #  - ./fastapi_backend/.env
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: bookstore_db
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: