version: "3.8"
services:
  api:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: "postgres"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: