version: "3.8"
services:
  api:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file:
      - .env
    # Dev volume
    # TODO: Make script to run in dev mode
    #volumes:
    #  - ./fastapi_backend/app:/app
    depends_on:
      - db

  db:
    image: "postgres"
    command: postgres -c 'max_connections=500'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: